sudo: required
services:
  - docker
before_install:
  - docker build -t kimlvu/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true kimlvu/react-test npm test
after_success:
  - docker build -t kimlvu/multi-client ./client
  - docker build -t kimlvu/multi-nginx ./nginx
  - docker build -t kimlvu/multi-server ./server
  - docker build -t kimlvu/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push kimlvu/multi-client
  - docker push kimlvu/multi-nginx
  - docker push kimlvu/multi-server
  - docker push kimlvu/multi-worker