sudo: required
services:
  - docker
before_install:
  - docker build -t kimlvu/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true kimlvu/react-test npm test
after_success:
  - docker build -t kimlvu/multi-client ./client
  - docker build -t kimlvu/multi-nginx ./nginx
  - docker build -t kimlvu/multi-server ./server
  - docker build -t kimlvu/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push kimlvu/multi-client
  - docker push kimlvu/multi-nginx
  - docker push kimlvu/multi-server
  - docker push kimlvu/multi-worker
deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-450921854464
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  


